### ISSUE TITLE
Remove quotes

### ISSUE THREAD

**Issue by pattrycja96** [kfk/grizly#121] opened 2019-09-25 11:26 UTC
Hi guys, 
Do we need "remove quotes" in loading data into RDS (this "COPY..." part)? Or could it be a parameter?

I have some issues with loading data (1:1 from Denodo into RDS) from delivery_scorecard_shipments_is (https://github.com/tedcs/booking_segmentation/issues/8). I can add some data only without this "remove quotes" and some only with this. We will look into it to find out other solution but for now we just want to know if it is necessary.

**Comment by michalz92** [comment] 2019-09-25 11:49
The best practice is to "sanitize" the data before uploading to Redshift. This is done by escaping any characters that might break it, such as quotes. The problem is, you'd have to run a script that adds an escape character before every quote in your data, and then run a script that strips these escape characters any time you download data from Redshift. 

So for our purposes, it's probably easier to add something like a try/except clause, one with `remove_quotes=False`, the other with `remove_quotes=True`.

**Comment by acivitillo** [comment] 2019-10-02 11:04
Can we create a CleanData class? Basically we create a class that takes a csv or df as an input and outputs a sanitized data source.
If you agree close the issue and create a task in grizly for this.

**Comment by pattrycja96** [comment] 2019-10-02 12:40
Yes, such a functionality would be helpful. We already have "df_clean(df)" (in etl in grizly) for dataframes. I am just wondering if it is better to just add another function for csv's files or have everything in one place and create a new class as you said.

**Comment by michalz92** [comment] 2019-10-09 13:43
We can try adding the ESCAPE keyword, which is supposed to escape quotes for us:

`REMOVEQUOTES ESCAPE`

**Comment by pattrycja96** [comment] 2019-10-14 07:54
Unfortunately I have the same error as before so I think I will stay with additional parameter remove_quotes=True/False.

**Comment by michalz92** [comment] 2019-10-14 08:36
Looks like it won't work without data preprocessing:

> With REMOVEQUOTES enabled, each column expects an opening and closing quote. In your case, if the data looked like
> 
> "someothercolumnvalue",',"anothercolumnvalue"
> 
> Redshift will strip the ' character and look for a matching '. Since it doesn't find one, it reports the error you encountered.
> 
> The fix is to put the ' character itself in quotes, ie "'"

So I guess for now we're stuck with using the parameter whenever required.

**Comment by michalz92** [comment] 2019-11-19 10:38
@pattrycja96 I think you found another solution, right? Could you share it/add to grizly?

**Comment by acivitillo** [comment] 2019-11-20 12:54
Can we create a Clean() class to take care of the crappy data things?

We could do

```python
df  = qframe.to_df()
df = Clean().from_df(df).to_df()
```

And add some standard cleaning inside from_df().

@pattrycja96 do you have a function already that does some data cleaning?

**Comment by michalz92** [comment] 2019-11-25 14:19
We've added the quote cleanup as a parameter to `s3_to_rds()`: `s3_to_rds(remove_inside_quotes=False)` with #226. I don't think this deserves a class since it can be solved with a single parameter.

**Comment by michalz92** [comment] 2019-11-25 14:22
Issue solved as per #209. Let's discuss the `Clean` class offline/in a separate issue if you want to follow up on that.

**Closed** 2019-11-25 14:22 UTC
Labels: bug
